sudo: required
language: node_js
node_js:
  - --lts
cache: skip
services:
  - docker
env:
  matrix:
    - NODE_CONTAINER=10.16-stretch
before_install:
  - docker pull node:$NODE_CONTAINER
install:
  - docker run -v $(pwd):/app node:$NODE_CONTAINER bash -c "cd app && yarn install"
script:
  - docker run -v $(pwd):/app node:$NODE_CONTAINER bash -c "cd app && yarn buildprod"
  - docker run -v $(pwd):/app node:$NODE_CONTAINER bash -c "cd app && yarn lint"
